import type { HazardZoneResult, PrintInputSummary, InputTier } from '../types';
// react-plotly.js CJS/ESM interop
import PlotlyModule from 'react-plotly.js';
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const Plot = ((PlotlyModule as any).default ?? PlotlyModule) as React.ComponentType<any>;

const M_TO_FT = 3.28084;
const TIER_LABELS: Record<InputTier, string> = {
  tier1: 'Tier 1 — Operator Mode (apogee only)',
  tier2: 'Tier 2 — Basic Geometry',
  tier3: 'Tier 3 — Full Geometry',
};

const BUILD_QUALITY_LABELS: Record<string, string> = {
  '1':    'Professional (×1.00)',
  '1.1':  'Good (×1.10)',
  '1.25': 'Average (×1.25)',
  '1.5':  'Poor (×1.50)',
};

// Inline style helpers — all light theme, no Tailwind dark utilities
const S = {
  page: {
    fontFamily: 'Georgia, serif',
    fontSize: '11px',
    lineHeight: '1.5',
    color: '#111',
    background: '#fff',
  } as React.CSSProperties,
  sectionHeader: {
    fontSize: '10px',
    fontWeight: 'bold',
    textTransform: 'uppercase' as const,
    letterSpacing: '.06em',
    color: '#333',
    borderBottom: '1px solid #ccc',
    paddingBottom: '3px',
    marginBottom: '7px',
  } as React.CSSProperties,
  pageFooter: {
    borderTop: '1px solid #ccc',
    paddingTop: '6px',
    marginTop: '16px',
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '8px',
    color: '#999',
  } as React.CSSProperties,
  page2: {
    pageBreakBefore: 'always',
  } as React.CSSProperties,
};

interface Props {
  result: HazardZoneResult;
  launchCoords: { lat: number; lon: number } | null;
  windBearing: number | null;
  inputSummary: PrintInputSummary | null;
  mapSnapshotUrl: string | null;
}

export function PrintView({ result, launchCoords, inputSummary, mapSnapshotUrl }: Props) {
  const r = result;
  const quarterFt = r.quarterAltitudeRule_m * M_TO_FT;
  const tier = inputSummary?.tier ?? 'tier1';

  // ── Trajectory traces (light theme) ──────────────────────────────────────
  const traces: object[] = [];
  if (r.trajectories) {
    const angles = Object.keys(r.trajectories).map(Number).sort((a, b) => a - b);
    for (const angle of angles) {
      const pts = r.trajectories[angle];
      if (!pts || pts.length === 0) continue;
      const isMax = angle === r.optimalAngle_deg;
      traces.push({
        x: pts.map(p => p.x * M_TO_FT),
        y: pts.map(p => Math.max(0, p.z) * M_TO_FT),
        type: 'scatter',
        mode: 'lines',
        name: `${angle}°`,
        line: { color: isMax ? '#2563eb' : '#94a3b8', width: isMax ? 2.5 : 1 },
        hoverinfo: 'skip',
      });
    }
  }
  if (r.hazardRadius_ft > 0) {
    traces.push({
      x: [r.hazardRadius_ft, r.hazardRadius_ft],
      y: [0, r.maxApogee_ft * 0.15],
      type: 'scatter',
      mode: 'lines',
      name: 'Hazard radius',
      line: { color: '#dc2626', width: 2, dash: 'dash' },
      hoverinfo: 'skip',
    });
  }

  const chartLayout = {
    paper_bgcolor: '#f8fafc',
    plot_bgcolor: '#f8fafc',
    font: { color: '#334155', size: 10, family: 'Georgia, serif' },
    xaxis: {
      title: { text: 'Downrange Distance (ft)', font: { size: 10 } },
      gridcolor: '#e2e8f0',
      zerolinecolor: '#94a3b8',
      rangemode: 'tozero' as const,
    },
    yaxis: {
      title: { text: 'Altitude AGL (ft)', font: { size: 10 } },
      gridcolor: '#e2e8f0',
      zerolinecolor: '#94a3b8',
      rangemode: 'tozero' as const,
    },
    margin: { l: 56, r: 16, t: 16, b: 48 },
    showlegend: true,
    legend: {
      bgcolor: 'rgba(248,250,252,0.9)',
      bordercolor: '#cbd5e1',
      borderwidth: 1,
      font: { size: 9 },
      x: 1, xanchor: 'right' as const, y: 1,
    },
    hovermode: false as const,
  };

  return (
    <div id="print-root" className="hidden print:block">

      {/* ── PAGE 1 ── */}
      <div style={S.page}>

        {/* Title block */}
        <div style={{ borderBottom: '2.5px solid #111', paddingBottom: '10px', marginBottom: '14px' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
            <div>
              <div style={{ fontSize: '17px', fontWeight: 'bold', textTransform: 'uppercase', letterSpacing: '.06em' }}>
                Hazard Zone Analysis Report
              </div>
              <div style={{ fontSize: '11px', color: '#444', marginTop: '2px', fontStyle: 'italic' }}>
                Amateur Rocketry — FAA AST Submittal
              </div>
            </div>
            <div style={{ textAlign: 'right', fontSize: '9px', color: '#555', lineHeight: '1.7' }}>
              <div><b>Date:</b> {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
              <div><b>Tier:</b> {TIER_LABELS[tier]}</div>
              <div><b>Generated by:</b> Hazard Zone Calculator v1.0</div>
            </div>
          </div>
          <div style={{ display: 'flex', gap: '24px', marginTop: '8px', fontSize: '9px', color: '#555', flexWrap: 'wrap' }}>
            {launchCoords && (
              <span><b>Launch site:</b> {launchCoords.lat.toFixed(5)}° N, {Math.abs(launchCoords.lon).toFixed(5)}° {launchCoords.lon < 0 ? 'W' : 'E'}</span>
            )}
            {inputSummary && <span><b>Site elevation:</b> {inputSummary.siteElevation_ft.toFixed(0)} ft MSL</span>}
            {inputSummary && <span><b>Max wind:</b> {inputSummary.maxWindSpeed_mph} MPH · <b>Max launch angle:</b> 20°</span>}
          </div>
        </div>

        {/* Warnings */}
        {r.warnings.length > 0 && (
          <div style={{ marginBottom: '14px' }}>
            {r.warnings.map((w, i) => (
              <div key={i} style={{ border: '1px solid #d97706', background: '#fffbeb', borderRadius: '4px', padding: '8px 10px', fontSize: '9px', color: '#92400e', marginBottom: '6px', pageBreakInside: 'avoid' }}>
                ⚠ {w}
              </div>
            ))}
          </div>
        )}

        {/* Methodology */}
        <div style={{ background: '#f8fafc', border: '1px solid #e2e8f0', borderRadius: '4px', padding: '10px', marginBottom: '14px', pageBreakInside: 'avoid' }}>
          <div style={{ fontSize: '10px', fontWeight: 'bold', color: '#334155', marginBottom: '4px' }}>Methodology</div>
          <div style={{ fontSize: '9px', color: '#555', lineHeight: '1.6' }}>
            3-DOF point-mass model (equivalent to TAOS, Sandia National Laboratories). Assumes nose-forward
            ballistic descent (conservative — lower drag than tumbling = longer range). CD estimated from body
            fineness ratio. Launch angle swept 0–20°, maximum wind speed 20 MPH. 1976 US Standard Atmosphere
            anchored to site elevation. Hazard radius = max(physics range, ¼ × apogee altitude).
          </div>
        </div>

        {/* Input Parameters */}
        {inputSummary && (
          <div style={{ marginBottom: '14px', pageBreakInside: 'avoid' }}>
            <div style={S.sectionHeader}>Input Parameters</div>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '9.5px' }}>
              <tbody>
                {tier === 'tier1' ? (
                  <>
                    <tr style={{ background: '#f5f7fa' }}>
                      <td style={{ padding: '4px 8px', color: '#555', width: '35%' }}>Apogee altitude</td>
                      <td style={{ padding: '4px 8px', fontWeight: 'bold' }}>{inputSummary.apogee_ft?.toFixed(0) ?? r.maxApogee_ft.toFixed(0)} ft</td>
                      <td style={{ padding: '4px 8px', color: '#555', width: '35%' }}>Site elevation</td>
                      <td style={{ padding: '4px 8px', fontWeight: 'bold' }}>{inputSummary.siteElevation_ft.toFixed(0)} ft MSL</td>
                    </tr>
                  </>
                ) : (
                  <>
                    <tr style={{ background: '#f5f7fa' }}>
                      <td style={{ padding: '4px 8px', color: '#555', width: '35%' }}>Rocket diameter</td>
                      <td style={{ padding: '4px 8px', fontWeight: 'bold' }}>{inputSummary.diameter_in?.toFixed(3)} in ({((inputSummary.diameter_in ?? 0) * 25.4).toFixed(1)} mm)</td>
                      <td style={{ padding: '4px 8px', color: '#555', width: '35%' }}>Body length</td>
                      <td style={{ padding: '4px 8px', fontWeight: 'bold' }}>{inputSummary.length_in?.toFixed(1)} in ({((inputSummary.length_in ?? 0) * 25.4).toFixed(0)} mm)</td>
                    </tr>
                    <tr>
                      <td style={{ padding: '4px 8px', color: '#555' }}>Gross mass</td>
                      <td style={{ padding: '4px 8px', fontWeight: 'bold' }}>{inputSummary.totalMass_lb?.toFixed(3)} lb ({((inputSummary.totalMass_lb ?? 0) * 453.592).toFixed(0)} g)</td>
                      <td style={{ padding: '4px 8px', color: '#555' }}>Motor</td>
                      <td style={{ padding: '4px 8px', fontWeight: 'bold' }}>{inputSummary.motorDesignation ?? '—'} (Class {r.motorClass})</td>
                    </tr>
                    <tr style={{ background: '#f5f7fa' }}>
                      <td style={{ padding: '4px 8px', color: '#555' }}>Total impulse</td>
                      <td style={{ padding: '4px 8px', fontWeight: 'bold' }}>{r.totalImpulse_Ns.toFixed(1)} N·s</td>
                      <td style={{ padding: '4px 8px', color: '#555' }}>CD source</td>
                      <td style={{ padding: '4px 8px', fontWeight: 'bold' }}>{inputSummary.cdSource ?? '—'}</td>
                    </tr>
                    {inputSummary.buildQualityMultiplier != null && inputSummary.buildQualityMultiplier !== 1.0 && (
                      <tr>
                        <td style={{ padding: '4px 8px', color: '#555' }}>Build quality</td>
                        <td style={{ padding: '4px 8px', fontWeight: 'bold' }}>
                          {BUILD_QUALITY_LABELS[String(inputSummary.buildQualityMultiplier)] ?? `×${inputSummary.buildQualityMultiplier}`}
                        </td>
                        <td style={{ padding: '4px 8px', color: '#555' }}>Effective CD</td>
                        <td style={{ padding: '4px 8px', fontWeight: 'bold' }}>{r.cdEffective?.toFixed(4) ?? '—'}</td>
                      </tr>
                    )}
                    {tier === 'tier3' && inputSummary.noseConeType && (
                      <tr style={{ background: '#f5f7fa' }}>
                        <td style={{ padding: '4px 8px', color: '#555' }}>Nose cone</td>
                        <td style={{ padding: '4px 8px', fontWeight: 'bold', textTransform: 'capitalize' }}>{inputSummary.noseConeType}</td>
                        <td style={{ padding: '4px 8px', color: '#555' }}>Number of fins</td>
                        <td style={{ padding: '4px 8px', fontWeight: 'bold' }}>{inputSummary.numFins ?? '—'}</td>
                      </tr>
                    )}
                  </>
                )}
              </tbody>
            </table>
          </div>
        )}

        {/* Results 2×2 */}
        <div style={{ marginBottom: '14px' }}>
          <div style={S.sectionHeader}>Results</div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '8px', pageBreakInside: 'avoid' }}>
            <div style={{ border: '2px solid #1d4ed8', background: '#eff6ff', borderRadius: '4px', padding: '10px', textAlign: 'center' }}>
              <div style={{ fontSize: '8.5px', color: '#555', textTransform: 'uppercase', letterSpacing: '.05em', marginBottom: '2px' }}>Hazard Zone Radius</div>
              <div style={{ fontSize: '22px', fontWeight: 'bold', color: '#1d4ed8', lineHeight: '1.1' }}>{r.hazardRadius_ft.toFixed(0)} ft</div>
              <div style={{ fontSize: '9px', color: '#888' }}>{r.hazardRadius_m.toFixed(0)} m</div>
            </div>
            <div style={{ border: '1px solid #ccc', borderRadius: '4px', padding: '10px', textAlign: 'center' }}>
              <div style={{ fontSize: '8.5px', color: '#555', textTransform: 'uppercase', letterSpacing: '.05em', marginBottom: '2px' }}>Maximum Apogee</div>
              <div style={{ fontSize: '22px', fontWeight: 'bold', lineHeight: '1.1' }}>{r.maxApogee_ft.toFixed(0)} ft</div>
              <div style={{ fontSize: '9px', color: '#888' }}>{r.maxApogee_m.toFixed(0)} m</div>
            </div>
            <div style={{ border: '1px solid #ccc', borderRadius: '4px', padding: '10px', textAlign: 'center' }}>
              <div style={{ fontSize: '8.5px', color: '#555', textTransform: 'uppercase', letterSpacing: '.05em', marginBottom: '2px' }}>Worst-case Launch Angle</div>
              <div style={{ fontSize: '22px', fontWeight: 'bold', lineHeight: '1.1' }}>{r.optimalAngle_deg}°</div>
              <div style={{ fontSize: '9px', color: '#888' }}>NAR/Tripoli max = 20°</div>
            </div>
            <div style={{ border: '1px solid #ccc', borderRadius: '4px', padding: '10px', textAlign: 'center' }}>
              <div style={{ fontSize: '8.5px', color: '#555', textTransform: 'uppercase', letterSpacing: '.05em', marginBottom: '2px' }}>Motor</div>
              <div style={{ fontSize: '16px', fontWeight: 'bold', lineHeight: '1.2' }}>
                {r.motorClass === '?' ? 'Unknown (Tier 1)' : `Class ${r.motorClass}`}
              </div>
              <div style={{ fontSize: '9px', color: '#888' }}>
                {r.totalImpulse_Ns > 0 ? `${r.totalImpulse_Ns.toFixed(0)} N·s total impulse` : 'Tier 1 — no motor input'}
              </div>
            </div>
          </div>
        </div>

        {/* ¼-altitude rule */}
        <div style={{
          border: `1px solid ${r.quarterRuleConservative ? '#059669' : '#d97706'}`,
          background: r.quarterRuleConservative ? '#ecfdf5' : '#fffbeb',
          borderRadius: '4px', padding: '10px', marginBottom: '14px',
          display: 'flex', justifyContent: 'space-between', alignItems: 'center',
          pageBreakInside: 'avoid',
        }}>
          <div>
            <div style={{ fontSize: '10px', fontWeight: 'bold', color: r.quarterRuleConservative ? '#065f46' : '#92400e' }}>NAR/Tripoli ¼-Altitude Rule Check</div>
            <div style={{ fontSize: '9px', color: '#555', marginTop: '2px' }}>
              Apogee {r.maxApogee_ft.toFixed(0)} ft ÷ 4 = {quarterFt.toFixed(0)} ft minimum clear zone
            </div>
          </div>
          <div style={{ textAlign: 'right' }}>
            <div style={{ fontSize: '10px', fontWeight: 'bold', color: r.quarterRuleConservative ? '#059669' : '#d97706' }}>
              {r.quarterRuleConservative ? 'Rule is conservative' : 'Physics exceeds ¼ rule'}
            </div>
            <div style={{ fontSize: '9px', color: '#555' }}>
              {r.quarterRuleConservative
                ? `${quarterFt.toFixed(0)} ft (rule) ≥ ${r.hazardRadius_ft.toFixed(0)} ft (physics)`
                : `Use ${r.hazardRadius_ft.toFixed(0)} ft — rule gives only ${quarterFt.toFixed(0)} ft`}
            </div>
          </div>
        </div>

        {/* Stability (Tier 2/3 only) */}
        {r.stabilityMargin_cal != null && r.stabilityCategory != null && (
          <div style={{
            border: `1px solid ${r.stabilityCategory === 'stable' ? '#059669' : r.stabilityCategory === 'marginal' ? '#d97706' : '#dc2626'}`,
            background: r.stabilityCategory === 'stable' ? '#ecfdf5' : r.stabilityCategory === 'marginal' ? '#fffbeb' : '#fef2f2',
            borderRadius: '4px', padding: '10px', marginBottom: '14px',
            display: 'flex', justifyContent: 'space-between', alignItems: 'center',
            pageBreakInside: 'avoid',
          }}>
            <div>
              <div style={{ fontSize: '10px', fontWeight: 'bold', color: r.stabilityCategory === 'stable' ? '#065f46' : r.stabilityCategory === 'marginal' ? '#92400e' : '#991b1b' }}>
                Static Stability Margin
              </div>
              <div style={{ fontSize: '9px', color: '#555', marginTop: '2px' }}>
                {r.stabilityMargin_cal.toFixed(2)} calibers
                {r.cdEffective != null && ` · Effective CD = ${r.cdEffective.toFixed(4)}`}
              </div>
            </div>
            <div style={{ textAlign: 'right' }}>
              <div style={{ fontSize: '10px', fontWeight: 'bold', color: r.stabilityCategory === 'stable' ? '#059669' : r.stabilityCategory === 'marginal' ? '#d97706' : '#dc2626' }}>
                {r.stabilityCategory === 'stable' ? 'Stable (≥ 1 cal)' : r.stabilityCategory === 'marginal' ? 'Marginal (0–1 cal)' : 'Unstable (< 0 cal)'}
              </div>
            </div>
          </div>
        )}

        {/* Page 1 footer */}
        <div style={S.pageFooter}>
          <span>3-DOF ballistic model · NAR/Tripoli safety envelope · 1976 US Standard Atmosphere</span>
          <span>Page 1 of 2</span>
        </div>
      </div>

      {/* ── PAGE 2 ── */}
      <div style={{ ...S.page, ...S.page2 }}>

        {/* Map */}
        <div style={{ marginBottom: '18px', pageBreakInside: 'avoid' }}>
          <div style={S.sectionHeader}>Launch Site — Hazard Zone Map</div>
          {mapSnapshotUrl ? (
            <>
              <img
                src={mapSnapshotUrl}
                alt="Hazard zone map"
                style={{ width: '100%', height: '220px', objectFit: 'cover', border: '1px solid #ccc', borderRadius: '4px', display: 'block' }}
              />
              <div style={{ fontSize: '8.5px', color: '#555', marginTop: '4px' }}>
                Red dashed circle = {r.hazardRadius_ft.toFixed(0)} ft ({r.hazardRadius_m.toFixed(0)} m) hazard radius · Blue dot = launch site · © OpenStreetMap contributors
              </div>
            </>
          ) : (
            /* Fallback when map fetch failed or no coords */
            <div style={{ border: '1px solid #ccc', borderRadius: '4px', padding: '12px', background: '#f8fafc' }}>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '6px', fontSize: '9.5px' }}>
                {launchCoords && (
                  <>
                    <div><span style={{ color: '#555' }}>Latitude: </span><b style={{ fontFamily: 'monospace' }}>{launchCoords.lat.toFixed(5)}° N</b></div>
                    <div><span style={{ color: '#555' }}>Longitude: </span><b style={{ fontFamily: 'monospace' }}>{Math.abs(launchCoords.lon).toFixed(5)}° {launchCoords.lon < 0 ? 'W' : 'E'}</b></div>
                  </>
                )}
                <div><span style={{ color: '#555' }}>Site elevation: </span><b>{inputSummary?.siteElevation_ft.toFixed(0) ?? '—'} ft MSL</b></div>
                <div><span style={{ color: '#555' }}>Hazard radius: </span><b style={{ color: '#1d4ed8' }}>{r.hazardRadius_ft.toFixed(0)} ft ({r.hazardRadius_m.toFixed(0)} m)</b></div>
              </div>
              <div style={{ marginTop: '8px', fontSize: '8px', color: '#888', fontStyle: 'italic' }}>
                Map image unavailable. See digital version for interactive map.
              </div>
            </div>
          )}
        </div>

        {/* Trajectory chart */}
        {traces.length > 0 && (
          <div style={{ marginBottom: '18px', pageBreakInside: 'avoid' }}>
            <div style={S.sectionHeader}>Ballistic Trajectory Sweep — Launch Angles 0°–20°</div>
            <Plot
              data={traces as never[]}
              layout={chartLayout}
              config={{ displayModeBar: false, responsive: false }}
              style={{ width: '100%', height: '280px' }}
            />
            <div style={{ fontSize: '8.5px', color: '#555', marginTop: '4px' }}>
              Blue = worst-case trajectory ({r.optimalAngle_deg}°) · Gray = other launch angles · Red dashed = hazard zone boundary · No recovery assumed
            </div>
          </div>
        )}

        {/* Tier 1 altitude range table */}
        {r.tier1Table && r.tier1Table.length > 0 && (
          <div style={{ marginBottom: '18px', pageBreakInside: 'avoid' }}>
            <div style={S.sectionHeader}>Altitude Range Table</div>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '9.5px' }}>
              <thead>
                <tr style={{ borderBottom: '1px solid #ccc' }}>
                  <th style={{ textAlign: 'left', padding: '4px 8px', color: '#555', fontWeight: 'normal', textTransform: 'uppercase', fontSize: '8px', letterSpacing: '.04em' }}>Apogee (ft AGL)</th>
                  <th style={{ textAlign: 'right', padding: '4px 8px', color: '#555', fontWeight: 'normal', textTransform: 'uppercase', fontSize: '8px', letterSpacing: '.04em' }}>Hazard Radius (ft)</th>
                  <th style={{ textAlign: 'right', padding: '4px 8px', color: '#555', fontWeight: 'normal', textTransform: 'uppercase', fontSize: '8px', letterSpacing: '.04em' }}>Hazard Radius (m)</th>
                </tr>
              </thead>
              <tbody>
                {r.tier1Table.map((row, i) => (
                  <tr key={row.altitude_ft} style={{ borderBottom: '1px solid #f0f0f0', background: i % 2 === 0 ? '#f8fafc' : '#fff' }}>
                    <td style={{ padding: '3px 8px', fontFamily: 'monospace' }}>{row.altitude_ft.toLocaleString()}</td>
                    <td style={{ padding: '3px 8px', textAlign: 'right', fontFamily: 'monospace' }}>{row.hazardRadius_ft.toFixed(0)}</td>
                    <td style={{ padding: '3px 8px', textAlign: 'right', fontFamily: 'monospace', color: '#555' }}>{row.hazardRadius_m.toFixed(0)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {/* Barrowman breakdown (Tier 3, no OR CSV) */}
        {r.barrowmanBreakdown && (
          <div style={{ marginBottom: '18px', pageBreakInside: 'avoid' }}>
            <div style={S.sectionHeader}>Barrowman CD Breakdown</div>
            <table style={{ width: '50%', borderCollapse: 'collapse', fontSize: '9.5px' }}>
              <tbody>
                {[
                  ['Skin friction (nose + body)', r.barrowmanBreakdown.CD_friction.toFixed(4)],
                  ['Base drag', r.barrowmanBreakdown.CD_base.toFixed(4)],
                  ['Fin drag', r.barrowmanBreakdown.CD_fins.toFixed(4)],
                  ['Nose pressure drag', r.barrowmanBreakdown.CD_nose_pressure.toFixed(4)],
                ].map(([label, val], i) => (
                  <tr key={label} style={{ background: i % 2 === 0 ? '#f8fafc' : '#fff' }}>
                    <td style={{ padding: '3px 8px', color: '#555' }}>{label}</td>
                    <td style={{ padding: '3px 8px', fontFamily: 'monospace', textAlign: 'right' }}>{val}</td>
                  </tr>
                ))}
                <tr style={{ borderTop: '1px solid #ccc' }}>
                  <td style={{ padding: '4px 8px', fontWeight: 'bold' }}>Total Barrowman CD</td>
                  <td style={{ padding: '4px 8px', fontFamily: 'monospace', textAlign: 'right', fontWeight: 'bold', color: '#1d4ed8' }}>{r.barrowmanBreakdown.CD_total.toFixed(4)}</td>
                </tr>
              </tbody>
            </table>
          </div>
        )}

        {/* OR apogee comparison */}
        {r.orkApogee_m != null && (
          <div style={{ marginBottom: '18px', pageBreakInside: 'avoid' }}>
            <div style={S.sectionHeader}>
              Apogee Comparison — Model vs OpenRocket
              {r.orkMotorDesignation && <span style={{ fontWeight: 'normal', marginLeft: '8px', color: '#888' }}>({r.orkMotorDesignation})</span>}
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '8px', textAlign: 'center', marginBottom: '8px' }}>
              <div style={{ border: '1px solid #ccc', borderRadius: '4px', padding: '8px' }}>
                <div style={{ fontSize: '8.5px', color: '#555', textTransform: 'uppercase', marginBottom: '4px' }}>Our model (3-DOF)</div>
                <div style={{ fontSize: '18px', fontWeight: 'bold', color: '#1d4ed8' }}>{r.maxApogee_ft.toFixed(0)} ft</div>
              </div>
              <div style={{ border: '1px solid #ccc', borderRadius: '4px', padding: '8px' }}>
                <div style={{ fontSize: '8.5px', color: '#555', textTransform: 'uppercase', marginBottom: '4px' }}>OpenRocket (stored)</div>
                <div style={{ fontSize: '18px', fontWeight: 'bold', color: '#7c3aed' }}>{(r.orkApogee_m * M_TO_FT).toFixed(0)} ft</div>
              </div>
            </div>
            {(() => {
              const pct = ((r.maxApogee_m - r.orkApogee_m!) / r.orkApogee_m!) * 100;
              const over = pct >= 0;
              return (
                <div style={{ textAlign: 'center', padding: '6px', border: `1px solid ${over ? '#059669' : '#d97706'}`, background: over ? '#ecfdf5' : '#fffbeb', borderRadius: '4px', fontSize: '9px', color: over ? '#065f46' : '#92400e' }}>
                  <b>{over ? '+' : ''}{pct.toFixed(1)}%</b> {over ? 'conservative overshoot' : 'undershooting OR — review inputs'}
                </div>
              );
            })()}
          </div>
        )}

        {/* Page 2 footer */}
        <div style={S.pageFooter}>
          <span>Hazard Zone Calculator v1.0</span>
          <span>Page 2 of 2</span>
        </div>
      </div>
    </div>
  );
}
